kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tomcat
  creationTimestamp:
  labels:
    run: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tomcat
  template:
    metadata:
      creationTimestamp:
      labels:
        run: tomcat
    spec:
      containers:
      - name: tomcat
        image: apache/tomcat-maven:1.0
        ports:
        - containerPort: 8080
        - containerPort: 8778
          name: jolokia
        - containerPort: 9404
          name: prometheus
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources: {}
  strategy: {}
status: {}
